### ISSUE TITLE
How do we get mapbox to send along session cookies with the Cross-Origin request?

### ISSUE THREAD

**Issue by maletor** [mapbox/corslite#12]
I'm trying to make a request to a resource server passing an access token that has my credentials in a shared cookie. If we can't pass the cookie we'll get a 401. Normally, with jQuery, we use `{ xhrFields: { withCredentials: true } }`

**Comment by jfirebaugh** [comment]
It's intentionally not possible with this library -- corslite supports only the lowest common denominator between XHR and XDomainRequest, and XDomainRequest does not support credentialed requests (see the fifth item [here](http://blogs.msdn.com/b/ieinternals/archive/2010/05/13/xdomainrequest-restrictions-limitations-and-workarounds.aspx?Redirected=true).

**Comment by jfirebaugh** [comment]
Note that if you don't need IE <10 support, you can use direct XHR, jQuery, or any other XHR library to make the request. At a higher level, most libraries (Mapbox.js included) provide APIs for supplying data directly, rather than making the request internally.
